# Generated by Django 4.1.5 on 2023-05-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAKEHOLDER', 'Stakeholder'), ('MANAGER', 'Manager'), ('ANALYST', 'Analyst'), ('CONSULTANT', 'Consultant'), ('CLIENT', 'Client')], default='CLIENT', max_length=11),
        ),
    ]
