# Generated by Django 4.1.5 on 2023-07-30 15:30

from django.db import migrations


class Migration(migrations.Migration):
    def link_employment_types(apps, schema_editor):
        Offer = apps.get_model("jobs", "JobOffer")
        EmploymentType = apps.get_model("jobs", "EmploymentType")
        for offer in Offer.objects.all():
            employment_type, _ = EmploymentType.objects.get_or_create(
                name=offer.employment_type
            )
            offer.employment_type_link = employment_type
            offer.save()

    dependencies = [
        ("jobs", "0004_joboffer_employment_type_link"),
    ]

    operations = [
        migrations.RunPython(link_employment_types),
    ]
