# Generated by Django 4.1.5 on 2023-07-31 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_populate_related_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='employment_type_link',
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='employment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.employmenttype'),
        ),
    ]
