# Generated by Django 4.1.5 on 2023-07-31 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_polishclassificationofactivities_industry'),
        ('jobs', '0006_remove_joboffer_employment_type_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='establishment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='krs',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='pca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_company', to='companies.polishclassificationofactivities'),
        ),
        migrations.AddField(
            model_name='company',
            name='regon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.legalform'),
        ),
    ]
