# Generated by Django 4.1.5 on 2023-08-01 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_joboffer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='nip',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='jobs.company'),
        ),
    ]
