# Generated by Django 4.1.5 on 2023-08-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_company_email_company_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
