# Generated by Django 4.1.5 on 2023-08-14 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_rename_phone_number_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
