# Generated by Django 4.1.5 on 2023-08-14 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_company_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='offer_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
