# Generated by Django 4.1.5 on 2023-08-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_joboffer_offer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='establishment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
