# Generated by Django 4.1.5 on 2023-08-24 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_company_establishment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='updated',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
