# Generated by Django 4.1.5 on 2023-08-27 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_alter_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='created',
            field=models.DateField(blank=True, default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='updated',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
