services:
  db:
    image: postgres
    env_file:
      - .env
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8080:8000"
    depends_on:
      - db
