# Generated by Django 4.1.5 on 2023-07-04 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('krs', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('regon', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address1', models.CharField(blank=True, max_length=60, null=True)),
                ('address2', models.CharField(blank=True, max_length=20, null=True)),
                ('zip', models.CharField(blank=True, max_length=6, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_range', models.IntegerField()),
                ('basic_legal_form', models.CharField(blank=True, max_length=1, null=True)),
                ('specific_legal_form', models.CharField(blank=True, max_length=3, null=True)),
                ('ownership_form', models.CharField(blank=True, max_length=3, null=True)),
                ('establishment_date', models.DateField()),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='companies/')),
            ],
        ),
        migrations.CreateModel(
            name='PolishClassificationOfActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=1)),
                ('department', models.CharField(max_length=2)),
                ('group', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=14)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='phone')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=60)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='email')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='pca',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.polishclassificationofactivities'),
        ),
    ]
