# Generated by Django 4.1.5 on 2023-07-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_regon'),
    ]

    operations = [
        migrations.AddField(
            model_name='polishclassificationofactivities',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
