# Generated by Django 4.1.5 on 2024-01-30 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_companystatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companystatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='companystatus',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='companies.company'),
        ),
    ]
