# Generated by Django 4.1.5 on 2024-01-30 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_remove_companystatus_id_alter_companystatus_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystatus',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status', serialize=False, to='companies.company'),
        ),
    ]
