# Generated by Django 4.1.5 on 2024-01-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_companystatus_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companystatus',
            name='taken',
        ),
    ]
