# Generated by Django 4.1.5 on 2024-01-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_remove_companystatus_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystatus',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
